(in-package :common-music)

(defgeneric mus-frequency (gen))   
(defgeneric (setf mus-frequency) (val gen))
(defgeneric mus-phase (gen))       
(defgeneric (setf mus-phase) (val gen))
(defgeneric mus-data (gen))        
(defgeneric (setf mus-data) (val gen))
(defgeneric mus-offset (gen))      
(defgeneric (setf mus-offset) (val gen))
(defgeneric mus-safety (gen))      
(defgeneric (setf mus-safety) (val gen))
(defgeneric mus-scaler (gen))      
(defgeneric (setf mus-scaler) (val gen))
(defgeneric mus-width (gen))       
(defgeneric (setf mus-width) (val gen))
(defgeneric mus-length (gen))      
(defgeneric (setf mus-length) (val gen))
(defgeneric mus-location (gen))    
(defgeneric (setf mus-location) (val gen))
(defgeneric mus-increment (gen))   
(defgeneric (setf mus-increment) (val gen))
(defgeneric mus-feedback (gen))    
(defgeneric (setf mus-feedback) (val gen))
(defgeneric mus-feedforward (gen)) 
(defgeneric (setf mus-feedforward) (val gen))
(defgeneric mus-order (gen))     
(defgeneric mus-xcoeffs (gen))
(defgeneric mus-ycoeffs (gen))
(defgeneric mus-channels (gen))
(defgeneric mus-channel (gen))     
(defgeneric (setf mus-channel) (val gen))
(defgeneric mus-hop (gen))         
(defgeneric (setf mus-hop) (val gen))
(defgeneric mus-ramp (gen))        
(defgeneric (setf mus-ramp) (val gen))
(defgeneric mus-interp-type (gen))
(defgeneric mus-xcoeff (gen index)) 
(defgeneric (setf mus-xcoeff) (val gen index))
(defgeneric mus-ycoeff (gen index)) 
(defgeneric (setf mus-ycoeff) (val gen index))
(defgeneric mus-describe (gen))
(defgeneric mus-file-name (gen))
(defgeneric mus-name (gen))        
(defgeneric (setf mus-name) (val gen))
(defgeneric mus-reset (gen))
(defgeneric oscil? (gen))
(defgeneric table-lookup? (gen))
(defgeneric delay? (gen))
(defgeneric comb? (gen))
(defgeneric filtered-comb? (gen))
(defgeneric notch? (gen))
(defgeneric all-pass? (gen))
(defgeneric moving-average? (gen))
(defgeneric filter? (gen))
(defgeneric fir-filter? (gen))
(defgeneric iir-filter? (gen))
(defgeneric one-zero? (gen))
(defgeneric one-pole? (gen))
(defgeneric two-pole? (gen))
(defgeneric two-zero? (gen))
(defgeneric firmant? (gen))
(defgeneric formant? (gen))
(defgeneric rand? (gen))
(defgeneric rand-interp? (gen))
(defgeneric env? (gen))
(defgeneric triangle-wave? (gen))
(defgeneric square-wave? (gen))
(defgeneric sawtooth-wave? (gen))
(defgeneric pulse-train? (gen))
(defgeneric polyshape? (gen))
(defgeneric polywave? (gen))
(defgeneric ncos? (gen))
(defgeneric nsin? (gen))
(defgeneric nrxycos? (gen))
(defgeneric nrxysin? (gen))
(defgeneric asymmetric-fm? (gen))
(defgeneric locsig? (gen))
(defgeneric move-sound? (gen))
(defgeneric file->sample? (gen))
(defgeneric mus-input? (gen))
(defgeneric file->frample? (gen))
(defgeneric sample->file? (gen))
(defgeneric mus-output? (gen))
(defgeneric frample->file? (gen))
(defgeneric readin? (gen))
;(defgeneric frame? (gen))
;(defgeneric mixer? (gen))
(defgeneric wave-train? (gen))
(defgeneric src? (gen))
(defgeneric convolve? (gen))
(defgeneric granulate? (gen))
(defgeneric phase-vocoder? (gen))
(defgeneric ssb-am? (gen))
;(defgeneric sample->frame (gen s &optional outf))
;(defgeneric frame->sample (gen fin))
(defgeneric mus-run (gen &optional arg1 arg2))