# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.23.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.23.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/joshuaarmenta/Documents/GitHub/common-tones

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/joshuaarmenta/Documents/GitHub/common-tones

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.23.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.23.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/joshuaarmenta/Documents/GitHub/common-tones/CMakeFiles /Users/joshuaarmenta/Documents/GitHub/common-tones//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/joshuaarmenta/Documents/GitHub/common-tones/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named common-tones

# Build rule for target.
common-tones: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 common-tones
.PHONY : common-tones

# fast build rule for target.
common-tones/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common-tones.dir/build.make CMakeFiles/common-tones.dir/build
.PHONY : common-tones/fast

src/audio.o: src/audio.c.o
.PHONY : src/audio.o

# target to build an object file
src/audio.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common-tones.dir/build.make CMakeFiles/common-tones.dir/src/audio.c.o
.PHONY : src/audio.c.o

src/audio.i: src/audio.c.i
.PHONY : src/audio.i

# target to preprocess a source file
src/audio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common-tones.dir/build.make CMakeFiles/common-tones.dir/src/audio.c.i
.PHONY : src/audio.c.i

src/audio.s: src/audio.c.s
.PHONY : src/audio.s

# target to generate assembly for a file
src/audio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common-tones.dir/build.make CMakeFiles/common-tones.dir/src/audio.c.s
.PHONY : src/audio.c.s

src/clm.o: src/clm.c.o
.PHONY : src/clm.o

# target to build an object file
src/clm.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common-tones.dir/build.make CMakeFiles/common-tones.dir/src/clm.c.o
.PHONY : src/clm.c.o

src/clm.i: src/clm.c.i
.PHONY : src/clm.i

# target to preprocess a source file
src/clm.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common-tones.dir/build.make CMakeFiles/common-tones.dir/src/clm.c.i
.PHONY : src/clm.c.i

src/clm.s: src/clm.c.s
.PHONY : src/clm.s

# target to generate assembly for a file
src/clm.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common-tones.dir/build.make CMakeFiles/common-tones.dir/src/clm.c.s
.PHONY : src/clm.c.s

src/cmus.o: src/cmus.c.o
.PHONY : src/cmus.o

# target to build an object file
src/cmus.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common-tones.dir/build.make CMakeFiles/common-tones.dir/src/cmus.c.o
.PHONY : src/cmus.c.o

src/cmus.i: src/cmus.c.i
.PHONY : src/cmus.i

# target to preprocess a source file
src/cmus.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common-tones.dir/build.make CMakeFiles/common-tones.dir/src/cmus.c.i
.PHONY : src/cmus.c.i

src/cmus.s: src/cmus.c.s
.PHONY : src/cmus.s

# target to generate assembly for a file
src/cmus.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common-tones.dir/build.make CMakeFiles/common-tones.dir/src/cmus.c.s
.PHONY : src/cmus.c.s

src/headers.o: src/headers.c.o
.PHONY : src/headers.o

# target to build an object file
src/headers.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common-tones.dir/build.make CMakeFiles/common-tones.dir/src/headers.c.o
.PHONY : src/headers.c.o

src/headers.i: src/headers.c.i
.PHONY : src/headers.i

# target to preprocess a source file
src/headers.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common-tones.dir/build.make CMakeFiles/common-tones.dir/src/headers.c.i
.PHONY : src/headers.c.i

src/headers.s: src/headers.c.s
.PHONY : src/headers.s

# target to generate assembly for a file
src/headers.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common-tones.dir/build.make CMakeFiles/common-tones.dir/src/headers.c.s
.PHONY : src/headers.c.s

src/io.o: src/io.c.o
.PHONY : src/io.o

# target to build an object file
src/io.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common-tones.dir/build.make CMakeFiles/common-tones.dir/src/io.c.o
.PHONY : src/io.c.o

src/io.i: src/io.c.i
.PHONY : src/io.i

# target to preprocess a source file
src/io.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common-tones.dir/build.make CMakeFiles/common-tones.dir/src/io.c.i
.PHONY : src/io.c.i

src/io.s: src/io.c.s
.PHONY : src/io.s

# target to generate assembly for a file
src/io.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common-tones.dir/build.make CMakeFiles/common-tones.dir/src/io.c.s
.PHONY : src/io.c.s

src/sound.o: src/sound.c.o
.PHONY : src/sound.o

# target to build an object file
src/sound.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common-tones.dir/build.make CMakeFiles/common-tones.dir/src/sound.c.o
.PHONY : src/sound.c.o

src/sound.i: src/sound.c.i
.PHONY : src/sound.i

# target to preprocess a source file
src/sound.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common-tones.dir/build.make CMakeFiles/common-tones.dir/src/sound.c.i
.PHONY : src/sound.c.i

src/sound.s: src/sound.c.s
.PHONY : src/sound.s

# target to generate assembly for a file
src/sound.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common-tones.dir/build.make CMakeFiles/common-tones.dir/src/sound.c.s
.PHONY : src/sound.c.s

src/vct.o: src/vct.c.o
.PHONY : src/vct.o

# target to build an object file
src/vct.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common-tones.dir/build.make CMakeFiles/common-tones.dir/src/vct.c.o
.PHONY : src/vct.c.o

src/vct.i: src/vct.c.i
.PHONY : src/vct.i

# target to preprocess a source file
src/vct.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common-tones.dir/build.make CMakeFiles/common-tones.dir/src/vct.c.i
.PHONY : src/vct.c.i

src/vct.s: src/vct.c.s
.PHONY : src/vct.s

# target to generate assembly for a file
src/vct.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common-tones.dir/build.make CMakeFiles/common-tones.dir/src/vct.c.s
.PHONY : src/vct.c.s

src/xen.o: src/xen.c.o
.PHONY : src/xen.o

# target to build an object file
src/xen.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common-tones.dir/build.make CMakeFiles/common-tones.dir/src/xen.c.o
.PHONY : src/xen.c.o

src/xen.i: src/xen.c.i
.PHONY : src/xen.i

# target to preprocess a source file
src/xen.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common-tones.dir/build.make CMakeFiles/common-tones.dir/src/xen.c.i
.PHONY : src/xen.c.i

src/xen.s: src/xen.c.s
.PHONY : src/xen.s

# target to generate assembly for a file
src/xen.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common-tones.dir/build.make CMakeFiles/common-tones.dir/src/xen.c.s
.PHONY : src/xen.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... common-tones"
	@echo "... src/audio.o"
	@echo "... src/audio.i"
	@echo "... src/audio.s"
	@echo "... src/clm.o"
	@echo "... src/clm.i"
	@echo "... src/clm.s"
	@echo "... src/cmus.o"
	@echo "... src/cmus.i"
	@echo "... src/cmus.s"
	@echo "... src/headers.o"
	@echo "... src/headers.i"
	@echo "... src/headers.s"
	@echo "... src/io.o"
	@echo "... src/io.i"
	@echo "... src/io.s"
	@echo "... src/sound.o"
	@echo "... src/sound.i"
	@echo "... src/sound.s"
	@echo "... src/vct.o"
	@echo "... src/vct.i"
	@echo "... src/vct.s"
	@echo "... src/xen.o"
	@echo "... src/xen.i"
	@echo "... src/xen.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

